{% set name = "pottery" %}
{% set version = "1.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cae794d217075276b1849553dd1db2eae4381265e35cbc3e2398343de7270ddb

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - redis-py >=3.4.1
    - mmh3
    - typing_extensions
  run:
    - python >=3.6
    - redis-py >=3.4.1
    - mmh3
    - typing_extensions

test:
  imports:
    - pottery

about:
  home: https://github.com/brainix/pottery
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pottery Redis for Humans
  dev_url: https://github.com/brainix/pottery

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - brnomendes
